---
- hosts: myserver
  become: true

  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == "Ubuntu"

    - name: Install Nginx
      ansible.builtin.package:
        name: nginx
        state: present
      notify: restart nginx

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginz
        state: reloaded
